name: 'Repository Manager'

on: [pull_request]

jobs:
  terraform:
    name: 'Terraform CDK Diff'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - run: yarn install
    - run: "mkdir .gen" # Will go away with one of the next versions of cdktf
    - name: Synth
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: "$(yarn bin)/cdktf synth"
    - name: Plan
      id: plan
      run: "cd cdktf.out && rm -rf .terraform && terraform init && terraform plan -no-color"
      continue-on-error: true
    - uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          const output = `#### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })